/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTreinarRouteImport } from './routes/app.treinar'
import { Route as AppProgressoRouteImport } from './routes/app.progresso'
import { Route as AppProfessorRouteImport } from './routes/app.professor'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppEstacoesRouteImport } from './routes/app.estacoes'
import { Route as AppProfessorIndexRouteImport } from './routes/app.professor.index'
import { Route as AppSimulacaoIdRouteImport } from './routes/app.simulacao.$id'
import { Route as AppResultadoIdRouteImport } from './routes/app.resultado.$id'
import { Route as AppProfessorEstacoesRouteImport } from './routes/app.professor.estacoes'
import { Route as AppProfessorCorrecoesRouteImport } from './routes/app.professor.correcoes'
import { Route as AppProfessorEstacoesIdRouteImport } from './routes/app.professor.estacoes.$id'
import { Route as AppProfessorCorrecoesIdRouteImport } from './routes/app.professor.correcoes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinarRoute = AppTreinarRouteImport.update({
  id: '/treinar',
  path: '/treinar',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressoRoute = AppProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessorRoute = AppProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppEstacoesRoute = AppEstacoesRouteImport.update({
  id: '/estacoes',
  path: '/estacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessorIndexRoute = AppProfessorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfessorRoute,
} as any)
const AppSimulacaoIdRoute = AppSimulacaoIdRouteImport.update({
  id: '/simulacao/$id',
  path: '/simulacao/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppResultadoIdRoute = AppResultadoIdRouteImport.update({
  id: '/resultado/$id',
  path: '/resultado/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessorEstacoesRoute = AppProfessorEstacoesRouteImport.update({
  id: '/estacoes',
  path: '/estacoes',
  getParentRoute: () => AppProfessorRoute,
} as any)
const AppProfessorCorrecoesRoute = AppProfessorCorrecoesRouteImport.update({
  id: '/correcoes',
  path: '/correcoes',
  getParentRoute: () => AppProfessorRoute,
} as any)
const AppProfessorEstacoesIdRoute = AppProfessorEstacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProfessorEstacoesRoute,
} as any)
const AppProfessorCorrecoesIdRoute = AppProfessorCorrecoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProfessorCorrecoesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/estacoes': typeof AppEstacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/professor': typeof AppProfessorRouteWithChildren
  '/app/progresso': typeof AppProgressoRoute
  '/app/treinar': typeof AppTreinarRoute
  '/app/': typeof AppIndexRoute
  '/app/professor/correcoes': typeof AppProfessorCorrecoesRouteWithChildren
  '/app/professor/estacoes': typeof AppProfessorEstacoesRouteWithChildren
  '/app/resultado/$id': typeof AppResultadoIdRoute
  '/app/simulacao/$id': typeof AppSimulacaoIdRoute
  '/app/professor/': typeof AppProfessorIndexRoute
  '/app/professor/correcoes/$id': typeof AppProfessorCorrecoesIdRoute
  '/app/professor/estacoes/$id': typeof AppProfessorEstacoesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/estacoes': typeof AppEstacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/progresso': typeof AppProgressoRoute
  '/app/treinar': typeof AppTreinarRoute
  '/app': typeof AppIndexRoute
  '/app/professor/correcoes': typeof AppProfessorCorrecoesRouteWithChildren
  '/app/professor/estacoes': typeof AppProfessorEstacoesRouteWithChildren
  '/app/resultado/$id': typeof AppResultadoIdRoute
  '/app/simulacao/$id': typeof AppSimulacaoIdRoute
  '/app/professor': typeof AppProfessorIndexRoute
  '/app/professor/correcoes/$id': typeof AppProfessorCorrecoesIdRoute
  '/app/professor/estacoes/$id': typeof AppProfessorEstacoesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/estacoes': typeof AppEstacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/professor': typeof AppProfessorRouteWithChildren
  '/app/progresso': typeof AppProgressoRoute
  '/app/treinar': typeof AppTreinarRoute
  '/app/': typeof AppIndexRoute
  '/app/professor/correcoes': typeof AppProfessorCorrecoesRouteWithChildren
  '/app/professor/estacoes': typeof AppProfessorEstacoesRouteWithChildren
  '/app/resultado/$id': typeof AppResultadoIdRoute
  '/app/simulacao/$id': typeof AppSimulacaoIdRoute
  '/app/professor/': typeof AppProfessorIndexRoute
  '/app/professor/correcoes/$id': typeof AppProfessorCorrecoesIdRoute
  '/app/professor/estacoes/$id': typeof AppProfessorEstacoesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/estacoes'
    | '/app/perfil'
    | '/app/professor'
    | '/app/progresso'
    | '/app/treinar'
    | '/app/'
    | '/app/professor/correcoes'
    | '/app/professor/estacoes'
    | '/app/resultado/$id'
    | '/app/simulacao/$id'
    | '/app/professor/'
    | '/app/professor/correcoes/$id'
    | '/app/professor/estacoes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/app/estacoes'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/treinar'
    | '/app'
    | '/app/professor/correcoes'
    | '/app/professor/estacoes'
    | '/app/resultado/$id'
    | '/app/simulacao/$id'
    | '/app/professor'
    | '/app/professor/correcoes/$id'
    | '/app/professor/estacoes/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/estacoes'
    | '/app/perfil'
    | '/app/professor'
    | '/app/progresso'
    | '/app/treinar'
    | '/app/'
    | '/app/professor/correcoes'
    | '/app/professor/estacoes'
    | '/app/resultado/$id'
    | '/app/simulacao/$id'
    | '/app/professor/'
    | '/app/professor/correcoes/$id'
    | '/app/professor/estacoes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/treinar': {
      id: '/app/treinar'
      path: '/treinar'
      fullPath: '/app/treinar'
      preLoaderRoute: typeof AppTreinarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progresso': {
      id: '/app/progresso'
      path: '/progresso'
      fullPath: '/app/progresso'
      preLoaderRoute: typeof AppProgressoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/professor': {
      id: '/app/professor'
      path: '/professor'
      fullPath: '/app/professor'
      preLoaderRoute: typeof AppProfessorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estacoes': {
      id: '/app/estacoes'
      path: '/estacoes'
      fullPath: '/app/estacoes'
      preLoaderRoute: typeof AppEstacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/professor/': {
      id: '/app/professor/'
      path: '/'
      fullPath: '/app/professor/'
      preLoaderRoute: typeof AppProfessorIndexRouteImport
      parentRoute: typeof AppProfessorRoute
    }
    '/app/simulacao/$id': {
      id: '/app/simulacao/$id'
      path: '/simulacao/$id'
      fullPath: '/app/simulacao/$id'
      preLoaderRoute: typeof AppSimulacaoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resultado/$id': {
      id: '/app/resultado/$id'
      path: '/resultado/$id'
      fullPath: '/app/resultado/$id'
      preLoaderRoute: typeof AppResultadoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/professor/estacoes': {
      id: '/app/professor/estacoes'
      path: '/estacoes'
      fullPath: '/app/professor/estacoes'
      preLoaderRoute: typeof AppProfessorEstacoesRouteImport
      parentRoute: typeof AppProfessorRoute
    }
    '/app/professor/correcoes': {
      id: '/app/professor/correcoes'
      path: '/correcoes'
      fullPath: '/app/professor/correcoes'
      preLoaderRoute: typeof AppProfessorCorrecoesRouteImport
      parentRoute: typeof AppProfessorRoute
    }
    '/app/professor/estacoes/$id': {
      id: '/app/professor/estacoes/$id'
      path: '/$id'
      fullPath: '/app/professor/estacoes/$id'
      preLoaderRoute: typeof AppProfessorEstacoesIdRouteImport
      parentRoute: typeof AppProfessorEstacoesRoute
    }
    '/app/professor/correcoes/$id': {
      id: '/app/professor/correcoes/$id'
      path: '/$id'
      fullPath: '/app/professor/correcoes/$id'
      preLoaderRoute: typeof AppProfessorCorrecoesIdRouteImport
      parentRoute: typeof AppProfessorCorrecoesRoute
    }
  }
}

interface AppProfessorCorrecoesRouteChildren {
  AppProfessorCorrecoesIdRoute: typeof AppProfessorCorrecoesIdRoute
}

const AppProfessorCorrecoesRouteChildren: AppProfessorCorrecoesRouteChildren = {
  AppProfessorCorrecoesIdRoute: AppProfessorCorrecoesIdRoute,
}

const AppProfessorCorrecoesRouteWithChildren =
  AppProfessorCorrecoesRoute._addFileChildren(
    AppProfessorCorrecoesRouteChildren,
  )

interface AppProfessorEstacoesRouteChildren {
  AppProfessorEstacoesIdRoute: typeof AppProfessorEstacoesIdRoute
}

const AppProfessorEstacoesRouteChildren: AppProfessorEstacoesRouteChildren = {
  AppProfessorEstacoesIdRoute: AppProfessorEstacoesIdRoute,
}

const AppProfessorEstacoesRouteWithChildren =
  AppProfessorEstacoesRoute._addFileChildren(AppProfessorEstacoesRouteChildren)

interface AppProfessorRouteChildren {
  AppProfessorCorrecoesRoute: typeof AppProfessorCorrecoesRouteWithChildren
  AppProfessorEstacoesRoute: typeof AppProfessorEstacoesRouteWithChildren
  AppProfessorIndexRoute: typeof AppProfessorIndexRoute
}

const AppProfessorRouteChildren: AppProfessorRouteChildren = {
  AppProfessorCorrecoesRoute: AppProfessorCorrecoesRouteWithChildren,
  AppProfessorEstacoesRoute: AppProfessorEstacoesRouteWithChildren,
  AppProfessorIndexRoute: AppProfessorIndexRoute,
}

const AppProfessorRouteWithChildren = AppProfessorRoute._addFileChildren(
  AppProfessorRouteChildren,
)

interface AppRouteChildren {
  AppEstacoesRoute: typeof AppEstacoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppProfessorRoute: typeof AppProfessorRouteWithChildren
  AppProgressoRoute: typeof AppProgressoRoute
  AppTreinarRoute: typeof AppTreinarRoute
  AppIndexRoute: typeof AppIndexRoute
  AppResultadoIdRoute: typeof AppResultadoIdRoute
  AppSimulacaoIdRoute: typeof AppSimulacaoIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEstacoesRoute: AppEstacoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppProfessorRoute: AppProfessorRouteWithChildren,
  AppProgressoRoute: AppProgressoRoute,
  AppTreinarRoute: AppTreinarRoute,
  AppIndexRoute: AppIndexRoute,
  AppResultadoIdRoute: AppResultadoIdRoute,
  AppSimulacaoIdRoute: AppSimulacaoIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
