/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ECodeRouteImport } from './routes/e.$code'
import { Route as ConviteCodeRouteImport } from './routes/convite.$code'
import { Route as AppVideoaulasRouteImport } from './routes/app.videoaulas'
import { Route as AppSuporteRouteImport } from './routes/app.suporte'
import { Route as AppResumosRouteImport } from './routes/app.resumos'
import { Route as AppProgressoRouteImport } from './routes/app.progresso'
import { Route as AppProfessorRouteImport } from './routes/app.professor'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppNovidadesRouteImport } from './routes/app.novidades'
import { Route as AppLiveRouteImport } from './routes/app.live'
import { Route as AppHistoricoRouteImport } from './routes/app.historico'
import { Route as AppFeedbackRouteImport } from './routes/app.feedback'
import { Route as AppCronogramaRouteImport } from './routes/app.cronograma'
import { Route as AppChecklistsRouteImport } from './routes/app.checklists'
import { Route as AppAulasRouteImport } from './routes/app.aulas'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppProfessorIndexRouteImport } from './routes/app.professor.index'
import { Route as AppFlashcardsIndexRouteImport } from './routes/app.flashcards.index'
import { Route as AppEntrarIndexRouteImport } from './routes/app.entrar.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppSimulacaoIdRouteImport } from './routes/app.simulacao.$id'
import { Route as AppSalaCodeRouteImport } from './routes/app.sala.$code'
import { Route as AppResumosIdRouteImport } from './routes/app.resumos.$id'
import { Route as AppResultadoIdRouteImport } from './routes/app.resultado.$id'
import { Route as AppProfessorResumosRouteImport } from './routes/app.professor.resumos'
import { Route as AppProfessorFlashcardsRouteImport } from './routes/app.professor.flashcards'
import { Route as AppProfessorEstacoesRouteImport } from './routes/app.professor.estacoes'
import { Route as AppProfessorCorrecoesRouteImport } from './routes/app.professor.correcoes'
import { Route as AppHistoricoIdRouteImport } from './routes/app.historico.$id'
import { Route as AppFlashcardsDesempenhoRouteImport } from './routes/app.flashcards.desempenho'
import { Route as AppEntrarCodeRouteImport } from './routes/app.entrar.$code'
import { Route as AppAdminUsuariosRouteImport } from './routes/app.admin.usuarios'
import { Route as AppAdminResumosRouteImport } from './routes/app.admin.resumos'
import { Route as AppAdminPlanosRouteImport } from './routes/app.admin.planos'
import { Route as AppAdminPagamentosRouteImport } from './routes/app.admin.pagamentos'
import { Route as AppAdminIntegracoesRouteImport } from './routes/app.admin.integracoes'
import { Route as AppAdminFlashcardsRouteImport } from './routes/app.admin.flashcards'
import { Route as AppAdminEstacoesRouteImport } from './routes/app.admin.estacoes'
import { Route as AppAdminConteudoRouteImport } from './routes/app.admin.conteudo'
import { Route as AppAdminAparenciaRouteImport } from './routes/app.admin.aparencia'
import { Route as AppSalaCodeIndexRouteImport } from './routes/app.sala.$code.index'
import { Route as AppAdminResumosIndexRouteImport } from './routes/app.admin.resumos.index'
import { Route as AppAdminFlashcardsIndexRouteImport } from './routes/app.admin.flashcards.index'
import { Route as AppAdminEstacoesIndexRouteImport } from './routes/app.admin.estacoes.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AppSalaCodePacienteRouteImport } from './routes/app.sala.$code.paciente'
import { Route as AppSalaCodeCandidatoRouteImport } from './routes/app.sala.$code.candidato'
import { Route as AppSalaCodeBancaRouteImport } from './routes/app.sala.$code.banca'
import { Route as AppProfessorEstacoesIdRouteImport } from './routes/app.professor.estacoes.$id'
import { Route as AppProfessorCorrecoesIdRouteImport } from './routes/app.professor.correcoes.$id'
import { Route as AppAdminResumosIdRouteImport } from './routes/app.admin.resumos.$id'
import { Route as AppAdminFlashcardsIdRouteImport } from './routes/app.admin.flashcards.$id'
import { Route as AppAdminEstacoesIdRouteImport } from './routes/app.admin.estacoes.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ECodeRoute = ECodeRouteImport.update({
  id: '/e/$code',
  path: '/e/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteCodeRoute = ConviteCodeRouteImport.update({
  id: '/convite/$code',
  path: '/convite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVideoaulasRoute = AppVideoaulasRouteImport.update({
  id: '/videoaulas',
  path: '/videoaulas',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppResumosRoute = AppResumosRouteImport.update({
  id: '/resumos',
  path: '/resumos',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressoRoute = AppProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessorRoute = AppProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNovidadesRoute = AppNovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppCronogramaRoute = AppCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistsRoute = AppChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => AppRoute,
} as any)
const AppAulasRoute = AppAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessorIndexRoute = AppProfessorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfessorRoute,
} as any)
const AppFlashcardsIndexRoute = AppFlashcardsIndexRouteImport.update({
  id: '/flashcards/',
  path: '/flashcards/',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrarIndexRoute = AppEntrarIndexRouteImport.update({
  id: '/entrar/',
  path: '/entrar/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppSimulacaoIdRoute = AppSimulacaoIdRouteImport.update({
  id: '/simulacao/$id',
  path: '/simulacao/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSalaCodeRoute = AppSalaCodeRouteImport.update({
  id: '/sala/$code',
  path: '/sala/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppResumosIdRoute = AppResumosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppResumosRoute,
} as any)
const AppResultadoIdRoute = AppResultadoIdRouteImport.update({
  id: '/resultado/$id',
  path: '/resultado/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessorResumosRoute = AppProfessorResumosRouteImport.update({
  id: '/resumos',
  path: '/resumos',
  getParentRoute: () => AppProfessorRoute,
} as any)
const AppProfessorFlashcardsRoute = AppProfessorFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppProfessorRoute,
} as any)
const AppProfessorEstacoesRoute = AppProfessorEstacoesRouteImport.update({
  id: '/estacoes',
  path: '/estacoes',
  getParentRoute: () => AppProfessorRoute,
} as any)
const AppProfessorCorrecoesRoute = AppProfessorCorrecoesRouteImport.update({
  id: '/correcoes',
  path: '/correcoes',
  getParentRoute: () => AppProfessorRoute,
} as any)
const AppHistoricoIdRoute = AppHistoricoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppHistoricoRoute,
} as any)
const AppFlashcardsDesempenhoRoute = AppFlashcardsDesempenhoRouteImport.update({
  id: '/flashcards/desempenho',
  path: '/flashcards/desempenho',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrarCodeRoute = AppEntrarCodeRouteImport.update({
  id: '/entrar/$code',
  path: '/entrar/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsuariosRoute = AppAdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminResumosRoute = AppAdminResumosRouteImport.update({
  id: '/resumos',
  path: '/resumos',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPlanosRoute = AppAdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPagamentosRoute = AppAdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminIntegracoesRoute = AppAdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFlashcardsRoute = AppAdminFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEstacoesRoute = AppAdminEstacoesRouteImport.update({
  id: '/estacoes',
  path: '/estacoes',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminConteudoRoute = AppAdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAparenciaRoute = AppAdminAparenciaRouteImport.update({
  id: '/aparencia',
  path: '/aparencia',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppSalaCodeIndexRoute = AppSalaCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalaCodeRoute,
} as any)
const AppAdminResumosIndexRoute = AppAdminResumosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminResumosRoute,
} as any)
const AppAdminFlashcardsIndexRoute = AppAdminFlashcardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminFlashcardsRoute,
} as any)
const AppAdminEstacoesIndexRoute = AppAdminEstacoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminEstacoesRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSalaCodePacienteRoute = AppSalaCodePacienteRouteImport.update({
  id: '/paciente',
  path: '/paciente',
  getParentRoute: () => AppSalaCodeRoute,
} as any)
const AppSalaCodeCandidatoRoute = AppSalaCodeCandidatoRouteImport.update({
  id: '/candidato',
  path: '/candidato',
  getParentRoute: () => AppSalaCodeRoute,
} as any)
const AppSalaCodeBancaRoute = AppSalaCodeBancaRouteImport.update({
  id: '/banca',
  path: '/banca',
  getParentRoute: () => AppSalaCodeRoute,
} as any)
const AppProfessorEstacoesIdRoute = AppProfessorEstacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProfessorEstacoesRoute,
} as any)
const AppProfessorCorrecoesIdRoute = AppProfessorCorrecoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProfessorCorrecoesRoute,
} as any)
const AppAdminResumosIdRoute = AppAdminResumosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminResumosRoute,
} as any)
const AppAdminFlashcardsIdRoute = AppAdminFlashcardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminFlashcardsRoute,
} as any)
const AppAdminEstacoesIdRoute = AppAdminEstacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminEstacoesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/aulas': typeof AppAulasRoute
  '/app/checklists': typeof AppChecklistsRoute
  '/app/cronograma': typeof AppCronogramaRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/historico': typeof AppHistoricoRouteWithChildren
  '/app/live': typeof AppLiveRoute
  '/app/novidades': typeof AppNovidadesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/professor': typeof AppProfessorRouteWithChildren
  '/app/progresso': typeof AppProgressoRoute
  '/app/resumos': typeof AppResumosRouteWithChildren
  '/app/suporte': typeof AppSuporteRoute
  '/app/videoaulas': typeof AppVideoaulasRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/e/$code': typeof ECodeRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/aparencia': typeof AppAdminAparenciaRoute
  '/app/admin/conteudo': typeof AppAdminConteudoRoute
  '/app/admin/estacoes': typeof AppAdminEstacoesRouteWithChildren
  '/app/admin/flashcards': typeof AppAdminFlashcardsRouteWithChildren
  '/app/admin/integracoes': typeof AppAdminIntegracoesRoute
  '/app/admin/pagamentos': typeof AppAdminPagamentosRoute
  '/app/admin/planos': typeof AppAdminPlanosRoute
  '/app/admin/resumos': typeof AppAdminResumosRouteWithChildren
  '/app/admin/usuarios': typeof AppAdminUsuariosRoute
  '/app/entrar/$code': typeof AppEntrarCodeRoute
  '/app/flashcards/desempenho': typeof AppFlashcardsDesempenhoRoute
  '/app/historico/$id': typeof AppHistoricoIdRoute
  '/app/professor/correcoes': typeof AppProfessorCorrecoesRouteWithChildren
  '/app/professor/estacoes': typeof AppProfessorEstacoesRouteWithChildren
  '/app/professor/flashcards': typeof AppProfessorFlashcardsRoute
  '/app/professor/resumos': typeof AppProfessorResumosRoute
  '/app/resultado/$id': typeof AppResultadoIdRoute
  '/app/resumos/$id': typeof AppResumosIdRoute
  '/app/sala/$code': typeof AppSalaCodeRouteWithChildren
  '/app/simulacao/$id': typeof AppSimulacaoIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/entrar/': typeof AppEntrarIndexRoute
  '/app/flashcards/': typeof AppFlashcardsIndexRoute
  '/app/professor/': typeof AppProfessorIndexRoute
  '/app/admin/estacoes/$id': typeof AppAdminEstacoesIdRoute
  '/app/admin/flashcards/$id': typeof AppAdminFlashcardsIdRoute
  '/app/admin/resumos/$id': typeof AppAdminResumosIdRoute
  '/app/professor/correcoes/$id': typeof AppProfessorCorrecoesIdRoute
  '/app/professor/estacoes/$id': typeof AppProfessorEstacoesIdRoute
  '/app/sala/$code/banca': typeof AppSalaCodeBancaRoute
  '/app/sala/$code/candidato': typeof AppSalaCodeCandidatoRoute
  '/app/sala/$code/paciente': typeof AppSalaCodePacienteRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/admin/estacoes/': typeof AppAdminEstacoesIndexRoute
  '/app/admin/flashcards/': typeof AppAdminFlashcardsIndexRoute
  '/app/admin/resumos/': typeof AppAdminResumosIndexRoute
  '/app/sala/$code/': typeof AppSalaCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/aulas': typeof AppAulasRoute
  '/app/checklists': typeof AppChecklistsRoute
  '/app/cronograma': typeof AppCronogramaRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/historico': typeof AppHistoricoRouteWithChildren
  '/app/live': typeof AppLiveRoute
  '/app/novidades': typeof AppNovidadesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/progresso': typeof AppProgressoRoute
  '/app/resumos': typeof AppResumosRouteWithChildren
  '/app/suporte': typeof AppSuporteRoute
  '/app/videoaulas': typeof AppVideoaulasRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/e/$code': typeof ECodeRoute
  '/app': typeof AppIndexRoute
  '/app/admin/aparencia': typeof AppAdminAparenciaRoute
  '/app/admin/conteudo': typeof AppAdminConteudoRoute
  '/app/admin/integracoes': typeof AppAdminIntegracoesRoute
  '/app/admin/pagamentos': typeof AppAdminPagamentosRoute
  '/app/admin/planos': typeof AppAdminPlanosRoute
  '/app/admin/usuarios': typeof AppAdminUsuariosRoute
  '/app/entrar/$code': typeof AppEntrarCodeRoute
  '/app/flashcards/desempenho': typeof AppFlashcardsDesempenhoRoute
  '/app/historico/$id': typeof AppHistoricoIdRoute
  '/app/professor/correcoes': typeof AppProfessorCorrecoesRouteWithChildren
  '/app/professor/estacoes': typeof AppProfessorEstacoesRouteWithChildren
  '/app/professor/flashcards': typeof AppProfessorFlashcardsRoute
  '/app/professor/resumos': typeof AppProfessorResumosRoute
  '/app/resultado/$id': typeof AppResultadoIdRoute
  '/app/resumos/$id': typeof AppResumosIdRoute
  '/app/simulacao/$id': typeof AppSimulacaoIdRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/entrar': typeof AppEntrarIndexRoute
  '/app/flashcards': typeof AppFlashcardsIndexRoute
  '/app/professor': typeof AppProfessorIndexRoute
  '/app/admin/estacoes/$id': typeof AppAdminEstacoesIdRoute
  '/app/admin/flashcards/$id': typeof AppAdminFlashcardsIdRoute
  '/app/admin/resumos/$id': typeof AppAdminResumosIdRoute
  '/app/professor/correcoes/$id': typeof AppProfessorCorrecoesIdRoute
  '/app/professor/estacoes/$id': typeof AppProfessorEstacoesIdRoute
  '/app/sala/$code/banca': typeof AppSalaCodeBancaRoute
  '/app/sala/$code/candidato': typeof AppSalaCodeCandidatoRoute
  '/app/sala/$code/paciente': typeof AppSalaCodePacienteRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/admin/estacoes': typeof AppAdminEstacoesIndexRoute
  '/app/admin/flashcards': typeof AppAdminFlashcardsIndexRoute
  '/app/admin/resumos': typeof AppAdminResumosIndexRoute
  '/app/sala/$code': typeof AppSalaCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/aulas': typeof AppAulasRoute
  '/app/checklists': typeof AppChecklistsRoute
  '/app/cronograma': typeof AppCronogramaRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/historico': typeof AppHistoricoRouteWithChildren
  '/app/live': typeof AppLiveRoute
  '/app/novidades': typeof AppNovidadesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/professor': typeof AppProfessorRouteWithChildren
  '/app/progresso': typeof AppProgressoRoute
  '/app/resumos': typeof AppResumosRouteWithChildren
  '/app/suporte': typeof AppSuporteRoute
  '/app/videoaulas': typeof AppVideoaulasRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/e/$code': typeof ECodeRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/aparencia': typeof AppAdminAparenciaRoute
  '/app/admin/conteudo': typeof AppAdminConteudoRoute
  '/app/admin/estacoes': typeof AppAdminEstacoesRouteWithChildren
  '/app/admin/flashcards': typeof AppAdminFlashcardsRouteWithChildren
  '/app/admin/integracoes': typeof AppAdminIntegracoesRoute
  '/app/admin/pagamentos': typeof AppAdminPagamentosRoute
  '/app/admin/planos': typeof AppAdminPlanosRoute
  '/app/admin/resumos': typeof AppAdminResumosRouteWithChildren
  '/app/admin/usuarios': typeof AppAdminUsuariosRoute
  '/app/entrar/$code': typeof AppEntrarCodeRoute
  '/app/flashcards/desempenho': typeof AppFlashcardsDesempenhoRoute
  '/app/historico/$id': typeof AppHistoricoIdRoute
  '/app/professor/correcoes': typeof AppProfessorCorrecoesRouteWithChildren
  '/app/professor/estacoes': typeof AppProfessorEstacoesRouteWithChildren
  '/app/professor/flashcards': typeof AppProfessorFlashcardsRoute
  '/app/professor/resumos': typeof AppProfessorResumosRoute
  '/app/resultado/$id': typeof AppResultadoIdRoute
  '/app/resumos/$id': typeof AppResumosIdRoute
  '/app/sala/$code': typeof AppSalaCodeRouteWithChildren
  '/app/simulacao/$id': typeof AppSimulacaoIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/entrar/': typeof AppEntrarIndexRoute
  '/app/flashcards/': typeof AppFlashcardsIndexRoute
  '/app/professor/': typeof AppProfessorIndexRoute
  '/app/admin/estacoes/$id': typeof AppAdminEstacoesIdRoute
  '/app/admin/flashcards/$id': typeof AppAdminFlashcardsIdRoute
  '/app/admin/resumos/$id': typeof AppAdminResumosIdRoute
  '/app/professor/correcoes/$id': typeof AppProfessorCorrecoesIdRoute
  '/app/professor/estacoes/$id': typeof AppProfessorEstacoesIdRoute
  '/app/sala/$code/banca': typeof AppSalaCodeBancaRoute
  '/app/sala/$code/candidato': typeof AppSalaCodeCandidatoRoute
  '/app/sala/$code/paciente': typeof AppSalaCodePacienteRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/admin/estacoes/': typeof AppAdminEstacoesIndexRoute
  '/app/admin/flashcards/': typeof AppAdminFlashcardsIndexRoute
  '/app/admin/resumos/': typeof AppAdminResumosIndexRoute
  '/app/sala/$code/': typeof AppSalaCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/reset-password'
    | '/app/admin'
    | '/app/aulas'
    | '/app/checklists'
    | '/app/cronograma'
    | '/app/feedback'
    | '/app/historico'
    | '/app/live'
    | '/app/novidades'
    | '/app/perfil'
    | '/app/professor'
    | '/app/progresso'
    | '/app/resumos'
    | '/app/suporte'
    | '/app/videoaulas'
    | '/convite/$code'
    | '/e/$code'
    | '/app/'
    | '/app/admin/aparencia'
    | '/app/admin/conteudo'
    | '/app/admin/estacoes'
    | '/app/admin/flashcards'
    | '/app/admin/integracoes'
    | '/app/admin/pagamentos'
    | '/app/admin/planos'
    | '/app/admin/resumos'
    | '/app/admin/usuarios'
    | '/app/entrar/$code'
    | '/app/flashcards/desempenho'
    | '/app/historico/$id'
    | '/app/professor/correcoes'
    | '/app/professor/estacoes'
    | '/app/professor/flashcards'
    | '/app/professor/resumos'
    | '/app/resultado/$id'
    | '/app/resumos/$id'
    | '/app/sala/$code'
    | '/app/simulacao/$id'
    | '/app/admin/'
    | '/app/entrar/'
    | '/app/flashcards/'
    | '/app/professor/'
    | '/app/admin/estacoes/$id'
    | '/app/admin/flashcards/$id'
    | '/app/admin/resumos/$id'
    | '/app/professor/correcoes/$id'
    | '/app/professor/estacoes/$id'
    | '/app/sala/$code/banca'
    | '/app/sala/$code/candidato'
    | '/app/sala/$code/paciente'
    | '/lovable/email/queue/process'
    | '/app/admin/estacoes/'
    | '/app/admin/flashcards/'
    | '/app/admin/resumos/'
    | '/app/sala/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/reset-password'
    | '/app/aulas'
    | '/app/checklists'
    | '/app/cronograma'
    | '/app/feedback'
    | '/app/historico'
    | '/app/live'
    | '/app/novidades'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/resumos'
    | '/app/suporte'
    | '/app/videoaulas'
    | '/convite/$code'
    | '/e/$code'
    | '/app'
    | '/app/admin/aparencia'
    | '/app/admin/conteudo'
    | '/app/admin/integracoes'
    | '/app/admin/pagamentos'
    | '/app/admin/planos'
    | '/app/admin/usuarios'
    | '/app/entrar/$code'
    | '/app/flashcards/desempenho'
    | '/app/historico/$id'
    | '/app/professor/correcoes'
    | '/app/professor/estacoes'
    | '/app/professor/flashcards'
    | '/app/professor/resumos'
    | '/app/resultado/$id'
    | '/app/resumos/$id'
    | '/app/simulacao/$id'
    | '/app/admin'
    | '/app/entrar'
    | '/app/flashcards'
    | '/app/professor'
    | '/app/admin/estacoes/$id'
    | '/app/admin/flashcards/$id'
    | '/app/admin/resumos/$id'
    | '/app/professor/correcoes/$id'
    | '/app/professor/estacoes/$id'
    | '/app/sala/$code/banca'
    | '/app/sala/$code/candidato'
    | '/app/sala/$code/paciente'
    | '/lovable/email/queue/process'
    | '/app/admin/estacoes'
    | '/app/admin/flashcards'
    | '/app/admin/resumos'
    | '/app/sala/$code'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/reset-password'
    | '/app/admin'
    | '/app/aulas'
    | '/app/checklists'
    | '/app/cronograma'
    | '/app/feedback'
    | '/app/historico'
    | '/app/live'
    | '/app/novidades'
    | '/app/perfil'
    | '/app/professor'
    | '/app/progresso'
    | '/app/resumos'
    | '/app/suporte'
    | '/app/videoaulas'
    | '/convite/$code'
    | '/e/$code'
    | '/app/'
    | '/app/admin/aparencia'
    | '/app/admin/conteudo'
    | '/app/admin/estacoes'
    | '/app/admin/flashcards'
    | '/app/admin/integracoes'
    | '/app/admin/pagamentos'
    | '/app/admin/planos'
    | '/app/admin/resumos'
    | '/app/admin/usuarios'
    | '/app/entrar/$code'
    | '/app/flashcards/desempenho'
    | '/app/historico/$id'
    | '/app/professor/correcoes'
    | '/app/professor/estacoes'
    | '/app/professor/flashcards'
    | '/app/professor/resumos'
    | '/app/resultado/$id'
    | '/app/resumos/$id'
    | '/app/sala/$code'
    | '/app/simulacao/$id'
    | '/app/admin/'
    | '/app/entrar/'
    | '/app/flashcards/'
    | '/app/professor/'
    | '/app/admin/estacoes/$id'
    | '/app/admin/flashcards/$id'
    | '/app/admin/resumos/$id'
    | '/app/professor/correcoes/$id'
    | '/app/professor/estacoes/$id'
    | '/app/sala/$code/banca'
    | '/app/sala/$code/candidato'
    | '/app/sala/$code/paciente'
    | '/lovable/email/queue/process'
    | '/app/admin/estacoes/'
    | '/app/admin/flashcards/'
    | '/app/admin/resumos/'
    | '/app/sala/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ConviteCodeRoute: typeof ConviteCodeRoute
  ECodeRoute: typeof ECodeRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/e/$code': {
      id: '/e/$code'
      path: '/e/$code'
      fullPath: '/e/$code'
      preLoaderRoute: typeof ECodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$code': {
      id: '/convite/$code'
      path: '/convite/$code'
      fullPath: '/convite/$code'
      preLoaderRoute: typeof ConviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/videoaulas': {
      id: '/app/videoaulas'
      path: '/videoaulas'
      fullPath: '/app/videoaulas'
      preLoaderRoute: typeof AppVideoaulasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resumos': {
      id: '/app/resumos'
      path: '/resumos'
      fullPath: '/app/resumos'
      preLoaderRoute: typeof AppResumosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progresso': {
      id: '/app/progresso'
      path: '/progresso'
      fullPath: '/app/progresso'
      preLoaderRoute: typeof AppProgressoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/professor': {
      id: '/app/professor'
      path: '/professor'
      fullPath: '/app/professor'
      preLoaderRoute: typeof AppProfessorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/novidades': {
      id: '/app/novidades'
      path: '/novidades'
      fullPath: '/app/novidades'
      preLoaderRoute: typeof AppNovidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/live': {
      id: '/app/live'
      path: '/live'
      fullPath: '/app/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico': {
      id: '/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feedback': {
      id: '/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cronograma': {
      id: '/app/cronograma'
      path: '/cronograma'
      fullPath: '/app/cronograma'
      preLoaderRoute: typeof AppCronogramaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checklists': {
      id: '/app/checklists'
      path: '/checklists'
      fullPath: '/app/checklists'
      preLoaderRoute: typeof AppChecklistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aulas': {
      id: '/app/aulas'
      path: '/aulas'
      fullPath: '/app/aulas'
      preLoaderRoute: typeof AppAulasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/professor/': {
      id: '/app/professor/'
      path: '/'
      fullPath: '/app/professor/'
      preLoaderRoute: typeof AppProfessorIndexRouteImport
      parentRoute: typeof AppProfessorRoute
    }
    '/app/flashcards/': {
      id: '/app/flashcards/'
      path: '/flashcards'
      fullPath: '/app/flashcards/'
      preLoaderRoute: typeof AppFlashcardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entrar/': {
      id: '/app/entrar/'
      path: '/entrar'
      fullPath: '/app/entrar/'
      preLoaderRoute: typeof AppEntrarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/simulacao/$id': {
      id: '/app/simulacao/$id'
      path: '/simulacao/$id'
      fullPath: '/app/simulacao/$id'
      preLoaderRoute: typeof AppSimulacaoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sala/$code': {
      id: '/app/sala/$code'
      path: '/sala/$code'
      fullPath: '/app/sala/$code'
      preLoaderRoute: typeof AppSalaCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resumos/$id': {
      id: '/app/resumos/$id'
      path: '/$id'
      fullPath: '/app/resumos/$id'
      preLoaderRoute: typeof AppResumosIdRouteImport
      parentRoute: typeof AppResumosRoute
    }
    '/app/resultado/$id': {
      id: '/app/resultado/$id'
      path: '/resultado/$id'
      fullPath: '/app/resultado/$id'
      preLoaderRoute: typeof AppResultadoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/professor/resumos': {
      id: '/app/professor/resumos'
      path: '/resumos'
      fullPath: '/app/professor/resumos'
      preLoaderRoute: typeof AppProfessorResumosRouteImport
      parentRoute: typeof AppProfessorRoute
    }
    '/app/professor/flashcards': {
      id: '/app/professor/flashcards'
      path: '/flashcards'
      fullPath: '/app/professor/flashcards'
      preLoaderRoute: typeof AppProfessorFlashcardsRouteImport
      parentRoute: typeof AppProfessorRoute
    }
    '/app/professor/estacoes': {
      id: '/app/professor/estacoes'
      path: '/estacoes'
      fullPath: '/app/professor/estacoes'
      preLoaderRoute: typeof AppProfessorEstacoesRouteImport
      parentRoute: typeof AppProfessorRoute
    }
    '/app/professor/correcoes': {
      id: '/app/professor/correcoes'
      path: '/correcoes'
      fullPath: '/app/professor/correcoes'
      preLoaderRoute: typeof AppProfessorCorrecoesRouteImport
      parentRoute: typeof AppProfessorRoute
    }
    '/app/historico/$id': {
      id: '/app/historico/$id'
      path: '/$id'
      fullPath: '/app/historico/$id'
      preLoaderRoute: typeof AppHistoricoIdRouteImport
      parentRoute: typeof AppHistoricoRoute
    }
    '/app/flashcards/desempenho': {
      id: '/app/flashcards/desempenho'
      path: '/flashcards/desempenho'
      fullPath: '/app/flashcards/desempenho'
      preLoaderRoute: typeof AppFlashcardsDesempenhoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entrar/$code': {
      id: '/app/entrar/$code'
      path: '/entrar/$code'
      fullPath: '/app/entrar/$code'
      preLoaderRoute: typeof AppEntrarCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/usuarios': {
      id: '/app/admin/usuarios'
      path: '/usuarios'
      fullPath: '/app/admin/usuarios'
      preLoaderRoute: typeof AppAdminUsuariosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/resumos': {
      id: '/app/admin/resumos'
      path: '/resumos'
      fullPath: '/app/admin/resumos'
      preLoaderRoute: typeof AppAdminResumosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/planos': {
      id: '/app/admin/planos'
      path: '/planos'
      fullPath: '/app/admin/planos'
      preLoaderRoute: typeof AppAdminPlanosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/pagamentos': {
      id: '/app/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/app/admin/pagamentos'
      preLoaderRoute: typeof AppAdminPagamentosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/integracoes': {
      id: '/app/admin/integracoes'
      path: '/integracoes'
      fullPath: '/app/admin/integracoes'
      preLoaderRoute: typeof AppAdminIntegracoesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/flashcards': {
      id: '/app/admin/flashcards'
      path: '/flashcards'
      fullPath: '/app/admin/flashcards'
      preLoaderRoute: typeof AppAdminFlashcardsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/estacoes': {
      id: '/app/admin/estacoes'
      path: '/estacoes'
      fullPath: '/app/admin/estacoes'
      preLoaderRoute: typeof AppAdminEstacoesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/conteudo': {
      id: '/app/admin/conteudo'
      path: '/conteudo'
      fullPath: '/app/admin/conteudo'
      preLoaderRoute: typeof AppAdminConteudoRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/aparencia': {
      id: '/app/admin/aparencia'
      path: '/aparencia'
      fullPath: '/app/admin/aparencia'
      preLoaderRoute: typeof AppAdminAparenciaRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/sala/$code/': {
      id: '/app/sala/$code/'
      path: '/'
      fullPath: '/app/sala/$code/'
      preLoaderRoute: typeof AppSalaCodeIndexRouteImport
      parentRoute: typeof AppSalaCodeRoute
    }
    '/app/admin/resumos/': {
      id: '/app/admin/resumos/'
      path: '/'
      fullPath: '/app/admin/resumos/'
      preLoaderRoute: typeof AppAdminResumosIndexRouteImport
      parentRoute: typeof AppAdminResumosRoute
    }
    '/app/admin/flashcards/': {
      id: '/app/admin/flashcards/'
      path: '/'
      fullPath: '/app/admin/flashcards/'
      preLoaderRoute: typeof AppAdminFlashcardsIndexRouteImport
      parentRoute: typeof AppAdminFlashcardsRoute
    }
    '/app/admin/estacoes/': {
      id: '/app/admin/estacoes/'
      path: '/'
      fullPath: '/app/admin/estacoes/'
      preLoaderRoute: typeof AppAdminEstacoesIndexRouteImport
      parentRoute: typeof AppAdminEstacoesRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sala/$code/paciente': {
      id: '/app/sala/$code/paciente'
      path: '/paciente'
      fullPath: '/app/sala/$code/paciente'
      preLoaderRoute: typeof AppSalaCodePacienteRouteImport
      parentRoute: typeof AppSalaCodeRoute
    }
    '/app/sala/$code/candidato': {
      id: '/app/sala/$code/candidato'
      path: '/candidato'
      fullPath: '/app/sala/$code/candidato'
      preLoaderRoute: typeof AppSalaCodeCandidatoRouteImport
      parentRoute: typeof AppSalaCodeRoute
    }
    '/app/sala/$code/banca': {
      id: '/app/sala/$code/banca'
      path: '/banca'
      fullPath: '/app/sala/$code/banca'
      preLoaderRoute: typeof AppSalaCodeBancaRouteImport
      parentRoute: typeof AppSalaCodeRoute
    }
    '/app/professor/estacoes/$id': {
      id: '/app/professor/estacoes/$id'
      path: '/$id'
      fullPath: '/app/professor/estacoes/$id'
      preLoaderRoute: typeof AppProfessorEstacoesIdRouteImport
      parentRoute: typeof AppProfessorEstacoesRoute
    }
    '/app/professor/correcoes/$id': {
      id: '/app/professor/correcoes/$id'
      path: '/$id'
      fullPath: '/app/professor/correcoes/$id'
      preLoaderRoute: typeof AppProfessorCorrecoesIdRouteImport
      parentRoute: typeof AppProfessorCorrecoesRoute
    }
    '/app/admin/resumos/$id': {
      id: '/app/admin/resumos/$id'
      path: '/$id'
      fullPath: '/app/admin/resumos/$id'
      preLoaderRoute: typeof AppAdminResumosIdRouteImport
      parentRoute: typeof AppAdminResumosRoute
    }
    '/app/admin/flashcards/$id': {
      id: '/app/admin/flashcards/$id'
      path: '/$id'
      fullPath: '/app/admin/flashcards/$id'
      preLoaderRoute: typeof AppAdminFlashcardsIdRouteImport
      parentRoute: typeof AppAdminFlashcardsRoute
    }
    '/app/admin/estacoes/$id': {
      id: '/app/admin/estacoes/$id'
      path: '/$id'
      fullPath: '/app/admin/estacoes/$id'
      preLoaderRoute: typeof AppAdminEstacoesIdRouteImport
      parentRoute: typeof AppAdminEstacoesRoute
    }
  }
}

interface AppAdminEstacoesRouteChildren {
  AppAdminEstacoesIdRoute: typeof AppAdminEstacoesIdRoute
  AppAdminEstacoesIndexRoute: typeof AppAdminEstacoesIndexRoute
}

const AppAdminEstacoesRouteChildren: AppAdminEstacoesRouteChildren = {
  AppAdminEstacoesIdRoute: AppAdminEstacoesIdRoute,
  AppAdminEstacoesIndexRoute: AppAdminEstacoesIndexRoute,
}

const AppAdminEstacoesRouteWithChildren =
  AppAdminEstacoesRoute._addFileChildren(AppAdminEstacoesRouteChildren)

interface AppAdminFlashcardsRouteChildren {
  AppAdminFlashcardsIdRoute: typeof AppAdminFlashcardsIdRoute
  AppAdminFlashcardsIndexRoute: typeof AppAdminFlashcardsIndexRoute
}

const AppAdminFlashcardsRouteChildren: AppAdminFlashcardsRouteChildren = {
  AppAdminFlashcardsIdRoute: AppAdminFlashcardsIdRoute,
  AppAdminFlashcardsIndexRoute: AppAdminFlashcardsIndexRoute,
}

const AppAdminFlashcardsRouteWithChildren =
  AppAdminFlashcardsRoute._addFileChildren(AppAdminFlashcardsRouteChildren)

interface AppAdminResumosRouteChildren {
  AppAdminResumosIdRoute: typeof AppAdminResumosIdRoute
  AppAdminResumosIndexRoute: typeof AppAdminResumosIndexRoute
}

const AppAdminResumosRouteChildren: AppAdminResumosRouteChildren = {
  AppAdminResumosIdRoute: AppAdminResumosIdRoute,
  AppAdminResumosIndexRoute: AppAdminResumosIndexRoute,
}

const AppAdminResumosRouteWithChildren = AppAdminResumosRoute._addFileChildren(
  AppAdminResumosRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminAparenciaRoute: typeof AppAdminAparenciaRoute
  AppAdminConteudoRoute: typeof AppAdminConteudoRoute
  AppAdminEstacoesRoute: typeof AppAdminEstacoesRouteWithChildren
  AppAdminFlashcardsRoute: typeof AppAdminFlashcardsRouteWithChildren
  AppAdminIntegracoesRoute: typeof AppAdminIntegracoesRoute
  AppAdminPagamentosRoute: typeof AppAdminPagamentosRoute
  AppAdminPlanosRoute: typeof AppAdminPlanosRoute
  AppAdminResumosRoute: typeof AppAdminResumosRouteWithChildren
  AppAdminUsuariosRoute: typeof AppAdminUsuariosRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAparenciaRoute: AppAdminAparenciaRoute,
  AppAdminConteudoRoute: AppAdminConteudoRoute,
  AppAdminEstacoesRoute: AppAdminEstacoesRouteWithChildren,
  AppAdminFlashcardsRoute: AppAdminFlashcardsRouteWithChildren,
  AppAdminIntegracoesRoute: AppAdminIntegracoesRoute,
  AppAdminPagamentosRoute: AppAdminPagamentosRoute,
  AppAdminPlanosRoute: AppAdminPlanosRoute,
  AppAdminResumosRoute: AppAdminResumosRouteWithChildren,
  AppAdminUsuariosRoute: AppAdminUsuariosRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppHistoricoRouteChildren {
  AppHistoricoIdRoute: typeof AppHistoricoIdRoute
}

const AppHistoricoRouteChildren: AppHistoricoRouteChildren = {
  AppHistoricoIdRoute: AppHistoricoIdRoute,
}

const AppHistoricoRouteWithChildren = AppHistoricoRoute._addFileChildren(
  AppHistoricoRouteChildren,
)

interface AppProfessorCorrecoesRouteChildren {
  AppProfessorCorrecoesIdRoute: typeof AppProfessorCorrecoesIdRoute
}

const AppProfessorCorrecoesRouteChildren: AppProfessorCorrecoesRouteChildren = {
  AppProfessorCorrecoesIdRoute: AppProfessorCorrecoesIdRoute,
}

const AppProfessorCorrecoesRouteWithChildren =
  AppProfessorCorrecoesRoute._addFileChildren(
    AppProfessorCorrecoesRouteChildren,
  )

interface AppProfessorEstacoesRouteChildren {
  AppProfessorEstacoesIdRoute: typeof AppProfessorEstacoesIdRoute
}

const AppProfessorEstacoesRouteChildren: AppProfessorEstacoesRouteChildren = {
  AppProfessorEstacoesIdRoute: AppProfessorEstacoesIdRoute,
}

const AppProfessorEstacoesRouteWithChildren =
  AppProfessorEstacoesRoute._addFileChildren(AppProfessorEstacoesRouteChildren)

interface AppProfessorRouteChildren {
  AppProfessorCorrecoesRoute: typeof AppProfessorCorrecoesRouteWithChildren
  AppProfessorEstacoesRoute: typeof AppProfessorEstacoesRouteWithChildren
  AppProfessorFlashcardsRoute: typeof AppProfessorFlashcardsRoute
  AppProfessorResumosRoute: typeof AppProfessorResumosRoute
  AppProfessorIndexRoute: typeof AppProfessorIndexRoute
}

const AppProfessorRouteChildren: AppProfessorRouteChildren = {
  AppProfessorCorrecoesRoute: AppProfessorCorrecoesRouteWithChildren,
  AppProfessorEstacoesRoute: AppProfessorEstacoesRouteWithChildren,
  AppProfessorFlashcardsRoute: AppProfessorFlashcardsRoute,
  AppProfessorResumosRoute: AppProfessorResumosRoute,
  AppProfessorIndexRoute: AppProfessorIndexRoute,
}

const AppProfessorRouteWithChildren = AppProfessorRoute._addFileChildren(
  AppProfessorRouteChildren,
)

interface AppResumosRouteChildren {
  AppResumosIdRoute: typeof AppResumosIdRoute
}

const AppResumosRouteChildren: AppResumosRouteChildren = {
  AppResumosIdRoute: AppResumosIdRoute,
}

const AppResumosRouteWithChildren = AppResumosRoute._addFileChildren(
  AppResumosRouteChildren,
)

interface AppSalaCodeRouteChildren {
  AppSalaCodeBancaRoute: typeof AppSalaCodeBancaRoute
  AppSalaCodeCandidatoRoute: typeof AppSalaCodeCandidatoRoute
  AppSalaCodePacienteRoute: typeof AppSalaCodePacienteRoute
  AppSalaCodeIndexRoute: typeof AppSalaCodeIndexRoute
}

const AppSalaCodeRouteChildren: AppSalaCodeRouteChildren = {
  AppSalaCodeBancaRoute: AppSalaCodeBancaRoute,
  AppSalaCodeCandidatoRoute: AppSalaCodeCandidatoRoute,
  AppSalaCodePacienteRoute: AppSalaCodePacienteRoute,
  AppSalaCodeIndexRoute: AppSalaCodeIndexRoute,
}

const AppSalaCodeRouteWithChildren = AppSalaCodeRoute._addFileChildren(
  AppSalaCodeRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAulasRoute: typeof AppAulasRoute
  AppChecklistsRoute: typeof AppChecklistsRoute
  AppCronogramaRoute: typeof AppCronogramaRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppHistoricoRoute: typeof AppHistoricoRouteWithChildren
  AppLiveRoute: typeof AppLiveRoute
  AppNovidadesRoute: typeof AppNovidadesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppProfessorRoute: typeof AppProfessorRouteWithChildren
  AppProgressoRoute: typeof AppProgressoRoute
  AppResumosRoute: typeof AppResumosRouteWithChildren
  AppSuporteRoute: typeof AppSuporteRoute
  AppVideoaulasRoute: typeof AppVideoaulasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEntrarCodeRoute: typeof AppEntrarCodeRoute
  AppFlashcardsDesempenhoRoute: typeof AppFlashcardsDesempenhoRoute
  AppResultadoIdRoute: typeof AppResultadoIdRoute
  AppSalaCodeRoute: typeof AppSalaCodeRouteWithChildren
  AppSimulacaoIdRoute: typeof AppSimulacaoIdRoute
  AppEntrarIndexRoute: typeof AppEntrarIndexRoute
  AppFlashcardsIndexRoute: typeof AppFlashcardsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAulasRoute: AppAulasRoute,
  AppChecklistsRoute: AppChecklistsRoute,
  AppCronogramaRoute: AppCronogramaRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppHistoricoRoute: AppHistoricoRouteWithChildren,
  AppLiveRoute: AppLiveRoute,
  AppNovidadesRoute: AppNovidadesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppProfessorRoute: AppProfessorRouteWithChildren,
  AppProgressoRoute: AppProgressoRoute,
  AppResumosRoute: AppResumosRouteWithChildren,
  AppSuporteRoute: AppSuporteRoute,
  AppVideoaulasRoute: AppVideoaulasRoute,
  AppIndexRoute: AppIndexRoute,
  AppEntrarCodeRoute: AppEntrarCodeRoute,
  AppFlashcardsDesempenhoRoute: AppFlashcardsDesempenhoRoute,
  AppResultadoIdRoute: AppResultadoIdRoute,
  AppSalaCodeRoute: AppSalaCodeRouteWithChildren,
  AppSimulacaoIdRoute: AppSimulacaoIdRoute,
  AppEntrarIndexRoute: AppEntrarIndexRoute,
  AppFlashcardsIndexRoute: AppFlashcardsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ConviteCodeRoute: ConviteCodeRoute,
  ECodeRoute: ECodeRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
