/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ECodeRouteImport } from './routes/e.$code'
import { Route as AppTreinarRouteImport } from './routes/app.treinar'
import { Route as AppResumosRouteImport } from './routes/app.resumos'
import { Route as AppProgressoRouteImport } from './routes/app.progresso'
import { Route as AppProfessorRouteImport } from './routes/app.professor'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppFlashcardsRouteImport } from './routes/app.flashcards'
import { Route as AppEstacoesRouteImport } from './routes/app.estacoes'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppProfessorIndexRouteImport } from './routes/app.professor.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppSimuladoIdRouteImport } from './routes/app.simulado.$id'
import { Route as AppSimulacaoIdRouteImport } from './routes/app.simulacao.$id'
import { Route as AppResumosIdRouteImport } from './routes/app.resumos.$id'
import { Route as AppResultadoIdRouteImport } from './routes/app.resultado.$id'
import { Route as AppProfessorResumosRouteImport } from './routes/app.professor.resumos'
import { Route as AppProfessorFlashcardsRouteImport } from './routes/app.professor.flashcards'
import { Route as AppProfessorEstacoesRouteImport } from './routes/app.professor.estacoes'
import { Route as AppProfessorCorrecoesRouteImport } from './routes/app.professor.correcoes'
import { Route as AppEntrarCodeRouteImport } from './routes/app.entrar.$code'
import { Route as AppAdminUsuariosRouteImport } from './routes/app.admin.usuarios'
import { Route as AppAdminPlanosRouteImport } from './routes/app.admin.planos'
import { Route as AppAdminEstacoesRouteImport } from './routes/app.admin.estacoes'
import { Route as AppAdminConteudoRouteImport } from './routes/app.admin.conteudo'
import { Route as AppSalaCodeIndexRouteImport } from './routes/app.sala.$code.index'
import { Route as AppSalaCodePacienteRouteImport } from './routes/app.sala.$code.paciente'
import { Route as AppSalaCodeCandidatoRouteImport } from './routes/app.sala.$code.candidato'
import { Route as AppSalaCodeBancaRouteImport } from './routes/app.sala.$code.banca'
import { Route as AppProfessorEstacoesIdRouteImport } from './routes/app.professor.estacoes.$id'
import { Route as AppProfessorCorrecoesIdRouteImport } from './routes/app.professor.correcoes.$id'
import { Route as AppAdminEstacoesIdRouteImport } from './routes/app.admin.estacoes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ECodeRoute = ECodeRouteImport.update({
  id: '/e/$code',
  path: '/e/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTreinarRoute = AppTreinarRouteImport.update({
  id: '/treinar',
  path: '/treinar',
  getParentRoute: () => AppRoute,
} as any)
const AppResumosRoute = AppResumosRouteImport.update({
  id: '/resumos',
  path: '/resumos',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressoRoute = AppProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessorRoute = AppProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppEstacoesRoute = AppEstacoesRouteImport.update({
  id: '/estacoes',
  path: '/estacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessorIndexRoute = AppProfessorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfessorRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppSimuladoIdRoute = AppSimuladoIdRouteImport.update({
  id: '/simulado/$id',
  path: '/simulado/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulacaoIdRoute = AppSimulacaoIdRouteImport.update({
  id: '/simulacao/$id',
  path: '/simulacao/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppResumosIdRoute = AppResumosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppResumosRoute,
} as any)
const AppResultadoIdRoute = AppResultadoIdRouteImport.update({
  id: '/resultado/$id',
  path: '/resultado/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessorResumosRoute = AppProfessorResumosRouteImport.update({
  id: '/resumos',
  path: '/resumos',
  getParentRoute: () => AppProfessorRoute,
} as any)
const AppProfessorFlashcardsRoute = AppProfessorFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppProfessorRoute,
} as any)
const AppProfessorEstacoesRoute = AppProfessorEstacoesRouteImport.update({
  id: '/estacoes',
  path: '/estacoes',
  getParentRoute: () => AppProfessorRoute,
} as any)
const AppProfessorCorrecoesRoute = AppProfessorCorrecoesRouteImport.update({
  id: '/correcoes',
  path: '/correcoes',
  getParentRoute: () => AppProfessorRoute,
} as any)
const AppEntrarCodeRoute = AppEntrarCodeRouteImport.update({
  id: '/entrar/$code',
  path: '/entrar/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsuariosRoute = AppAdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPlanosRoute = AppAdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEstacoesRoute = AppAdminEstacoesRouteImport.update({
  id: '/estacoes',
  path: '/estacoes',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminConteudoRoute = AppAdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppSalaCodeIndexRoute = AppSalaCodeIndexRouteImport.update({
  id: '/sala/$code/',
  path: '/sala/$code/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalaCodePacienteRoute = AppSalaCodePacienteRouteImport.update({
  id: '/sala/$code/paciente',
  path: '/sala/$code/paciente',
  getParentRoute: () => AppRoute,
} as any)
const AppSalaCodeCandidatoRoute = AppSalaCodeCandidatoRouteImport.update({
  id: '/sala/$code/candidato',
  path: '/sala/$code/candidato',
  getParentRoute: () => AppRoute,
} as any)
const AppSalaCodeBancaRoute = AppSalaCodeBancaRouteImport.update({
  id: '/sala/$code/banca',
  path: '/sala/$code/banca',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessorEstacoesIdRoute = AppProfessorEstacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProfessorEstacoesRoute,
} as any)
const AppProfessorCorrecoesIdRoute = AppProfessorCorrecoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProfessorCorrecoesRoute,
} as any)
const AppAdminEstacoesIdRoute = AppAdminEstacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminEstacoesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/estacoes': typeof AppEstacoesRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/professor': typeof AppProfessorRouteWithChildren
  '/app/progresso': typeof AppProgressoRoute
  '/app/resumos': typeof AppResumosRouteWithChildren
  '/app/treinar': typeof AppTreinarRoute
  '/e/$code': typeof ECodeRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/conteudo': typeof AppAdminConteudoRoute
  '/app/admin/estacoes': typeof AppAdminEstacoesRouteWithChildren
  '/app/admin/planos': typeof AppAdminPlanosRoute
  '/app/admin/usuarios': typeof AppAdminUsuariosRoute
  '/app/entrar/$code': typeof AppEntrarCodeRoute
  '/app/professor/correcoes': typeof AppProfessorCorrecoesRouteWithChildren
  '/app/professor/estacoes': typeof AppProfessorEstacoesRouteWithChildren
  '/app/professor/flashcards': typeof AppProfessorFlashcardsRoute
  '/app/professor/resumos': typeof AppProfessorResumosRoute
  '/app/resultado/$id': typeof AppResultadoIdRoute
  '/app/resumos/$id': typeof AppResumosIdRoute
  '/app/simulacao/$id': typeof AppSimulacaoIdRoute
  '/app/simulado/$id': typeof AppSimuladoIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/professor/': typeof AppProfessorIndexRoute
  '/app/admin/estacoes/$id': typeof AppAdminEstacoesIdRoute
  '/app/professor/correcoes/$id': typeof AppProfessorCorrecoesIdRoute
  '/app/professor/estacoes/$id': typeof AppProfessorEstacoesIdRoute
  '/app/sala/$code/banca': typeof AppSalaCodeBancaRoute
  '/app/sala/$code/candidato': typeof AppSalaCodeCandidatoRoute
  '/app/sala/$code/paciente': typeof AppSalaCodePacienteRoute
  '/app/sala/$code/': typeof AppSalaCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/estacoes': typeof AppEstacoesRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/progresso': typeof AppProgressoRoute
  '/app/resumos': typeof AppResumosRouteWithChildren
  '/app/treinar': typeof AppTreinarRoute
  '/e/$code': typeof ECodeRoute
  '/app': typeof AppIndexRoute
  '/app/admin/conteudo': typeof AppAdminConteudoRoute
  '/app/admin/estacoes': typeof AppAdminEstacoesRouteWithChildren
  '/app/admin/planos': typeof AppAdminPlanosRoute
  '/app/admin/usuarios': typeof AppAdminUsuariosRoute
  '/app/entrar/$code': typeof AppEntrarCodeRoute
  '/app/professor/correcoes': typeof AppProfessorCorrecoesRouteWithChildren
  '/app/professor/estacoes': typeof AppProfessorEstacoesRouteWithChildren
  '/app/professor/flashcards': typeof AppProfessorFlashcardsRoute
  '/app/professor/resumos': typeof AppProfessorResumosRoute
  '/app/resultado/$id': typeof AppResultadoIdRoute
  '/app/resumos/$id': typeof AppResumosIdRoute
  '/app/simulacao/$id': typeof AppSimulacaoIdRoute
  '/app/simulado/$id': typeof AppSimuladoIdRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/professor': typeof AppProfessorIndexRoute
  '/app/admin/estacoes/$id': typeof AppAdminEstacoesIdRoute
  '/app/professor/correcoes/$id': typeof AppProfessorCorrecoesIdRoute
  '/app/professor/estacoes/$id': typeof AppProfessorEstacoesIdRoute
  '/app/sala/$code/banca': typeof AppSalaCodeBancaRoute
  '/app/sala/$code/candidato': typeof AppSalaCodeCandidatoRoute
  '/app/sala/$code/paciente': typeof AppSalaCodePacienteRoute
  '/app/sala/$code': typeof AppSalaCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/estacoes': typeof AppEstacoesRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/professor': typeof AppProfessorRouteWithChildren
  '/app/progresso': typeof AppProgressoRoute
  '/app/resumos': typeof AppResumosRouteWithChildren
  '/app/treinar': typeof AppTreinarRoute
  '/e/$code': typeof ECodeRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/conteudo': typeof AppAdminConteudoRoute
  '/app/admin/estacoes': typeof AppAdminEstacoesRouteWithChildren
  '/app/admin/planos': typeof AppAdminPlanosRoute
  '/app/admin/usuarios': typeof AppAdminUsuariosRoute
  '/app/entrar/$code': typeof AppEntrarCodeRoute
  '/app/professor/correcoes': typeof AppProfessorCorrecoesRouteWithChildren
  '/app/professor/estacoes': typeof AppProfessorEstacoesRouteWithChildren
  '/app/professor/flashcards': typeof AppProfessorFlashcardsRoute
  '/app/professor/resumos': typeof AppProfessorResumosRoute
  '/app/resultado/$id': typeof AppResultadoIdRoute
  '/app/resumos/$id': typeof AppResumosIdRoute
  '/app/simulacao/$id': typeof AppSimulacaoIdRoute
  '/app/simulado/$id': typeof AppSimuladoIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/professor/': typeof AppProfessorIndexRoute
  '/app/admin/estacoes/$id': typeof AppAdminEstacoesIdRoute
  '/app/professor/correcoes/$id': typeof AppProfessorCorrecoesIdRoute
  '/app/professor/estacoes/$id': typeof AppProfessorEstacoesIdRoute
  '/app/sala/$code/banca': typeof AppSalaCodeBancaRoute
  '/app/sala/$code/candidato': typeof AppSalaCodeCandidatoRoute
  '/app/sala/$code/paciente': typeof AppSalaCodePacienteRoute
  '/app/sala/$code/': typeof AppSalaCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/admin'
    | '/app/estacoes'
    | '/app/flashcards'
    | '/app/perfil'
    | '/app/professor'
    | '/app/progresso'
    | '/app/resumos'
    | '/app/treinar'
    | '/e/$code'
    | '/app/'
    | '/app/admin/conteudo'
    | '/app/admin/estacoes'
    | '/app/admin/planos'
    | '/app/admin/usuarios'
    | '/app/entrar/$code'
    | '/app/professor/correcoes'
    | '/app/professor/estacoes'
    | '/app/professor/flashcards'
    | '/app/professor/resumos'
    | '/app/resultado/$id'
    | '/app/resumos/$id'
    | '/app/simulacao/$id'
    | '/app/simulado/$id'
    | '/app/admin/'
    | '/app/professor/'
    | '/app/admin/estacoes/$id'
    | '/app/professor/correcoes/$id'
    | '/app/professor/estacoes/$id'
    | '/app/sala/$code/banca'
    | '/app/sala/$code/candidato'
    | '/app/sala/$code/paciente'
    | '/app/sala/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/app/estacoes'
    | '/app/flashcards'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/resumos'
    | '/app/treinar'
    | '/e/$code'
    | '/app'
    | '/app/admin/conteudo'
    | '/app/admin/estacoes'
    | '/app/admin/planos'
    | '/app/admin/usuarios'
    | '/app/entrar/$code'
    | '/app/professor/correcoes'
    | '/app/professor/estacoes'
    | '/app/professor/flashcards'
    | '/app/professor/resumos'
    | '/app/resultado/$id'
    | '/app/resumos/$id'
    | '/app/simulacao/$id'
    | '/app/simulado/$id'
    | '/app/admin'
    | '/app/professor'
    | '/app/admin/estacoes/$id'
    | '/app/professor/correcoes/$id'
    | '/app/professor/estacoes/$id'
    | '/app/sala/$code/banca'
    | '/app/sala/$code/candidato'
    | '/app/sala/$code/paciente'
    | '/app/sala/$code'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/admin'
    | '/app/estacoes'
    | '/app/flashcards'
    | '/app/perfil'
    | '/app/professor'
    | '/app/progresso'
    | '/app/resumos'
    | '/app/treinar'
    | '/e/$code'
    | '/app/'
    | '/app/admin/conteudo'
    | '/app/admin/estacoes'
    | '/app/admin/planos'
    | '/app/admin/usuarios'
    | '/app/entrar/$code'
    | '/app/professor/correcoes'
    | '/app/professor/estacoes'
    | '/app/professor/flashcards'
    | '/app/professor/resumos'
    | '/app/resultado/$id'
    | '/app/resumos/$id'
    | '/app/simulacao/$id'
    | '/app/simulado/$id'
    | '/app/admin/'
    | '/app/professor/'
    | '/app/admin/estacoes/$id'
    | '/app/professor/correcoes/$id'
    | '/app/professor/estacoes/$id'
    | '/app/sala/$code/banca'
    | '/app/sala/$code/candidato'
    | '/app/sala/$code/paciente'
    | '/app/sala/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  ECodeRoute: typeof ECodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/e/$code': {
      id: '/e/$code'
      path: '/e/$code'
      fullPath: '/e/$code'
      preLoaderRoute: typeof ECodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/treinar': {
      id: '/app/treinar'
      path: '/treinar'
      fullPath: '/app/treinar'
      preLoaderRoute: typeof AppTreinarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resumos': {
      id: '/app/resumos'
      path: '/resumos'
      fullPath: '/app/resumos'
      preLoaderRoute: typeof AppResumosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progresso': {
      id: '/app/progresso'
      path: '/progresso'
      fullPath: '/app/progresso'
      preLoaderRoute: typeof AppProgressoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/professor': {
      id: '/app/professor'
      path: '/professor'
      fullPath: '/app/professor'
      preLoaderRoute: typeof AppProfessorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flashcards': {
      id: '/app/flashcards'
      path: '/flashcards'
      fullPath: '/app/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estacoes': {
      id: '/app/estacoes'
      path: '/estacoes'
      fullPath: '/app/estacoes'
      preLoaderRoute: typeof AppEstacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/professor/': {
      id: '/app/professor/'
      path: '/'
      fullPath: '/app/professor/'
      preLoaderRoute: typeof AppProfessorIndexRouteImport
      parentRoute: typeof AppProfessorRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/simulado/$id': {
      id: '/app/simulado/$id'
      path: '/simulado/$id'
      fullPath: '/app/simulado/$id'
      preLoaderRoute: typeof AppSimuladoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulacao/$id': {
      id: '/app/simulacao/$id'
      path: '/simulacao/$id'
      fullPath: '/app/simulacao/$id'
      preLoaderRoute: typeof AppSimulacaoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resumos/$id': {
      id: '/app/resumos/$id'
      path: '/$id'
      fullPath: '/app/resumos/$id'
      preLoaderRoute: typeof AppResumosIdRouteImport
      parentRoute: typeof AppResumosRoute
    }
    '/app/resultado/$id': {
      id: '/app/resultado/$id'
      path: '/resultado/$id'
      fullPath: '/app/resultado/$id'
      preLoaderRoute: typeof AppResultadoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/professor/resumos': {
      id: '/app/professor/resumos'
      path: '/resumos'
      fullPath: '/app/professor/resumos'
      preLoaderRoute: typeof AppProfessorResumosRouteImport
      parentRoute: typeof AppProfessorRoute
    }
    '/app/professor/flashcards': {
      id: '/app/professor/flashcards'
      path: '/flashcards'
      fullPath: '/app/professor/flashcards'
      preLoaderRoute: typeof AppProfessorFlashcardsRouteImport
      parentRoute: typeof AppProfessorRoute
    }
    '/app/professor/estacoes': {
      id: '/app/professor/estacoes'
      path: '/estacoes'
      fullPath: '/app/professor/estacoes'
      preLoaderRoute: typeof AppProfessorEstacoesRouteImport
      parentRoute: typeof AppProfessorRoute
    }
    '/app/professor/correcoes': {
      id: '/app/professor/correcoes'
      path: '/correcoes'
      fullPath: '/app/professor/correcoes'
      preLoaderRoute: typeof AppProfessorCorrecoesRouteImport
      parentRoute: typeof AppProfessorRoute
    }
    '/app/entrar/$code': {
      id: '/app/entrar/$code'
      path: '/entrar/$code'
      fullPath: '/app/entrar/$code'
      preLoaderRoute: typeof AppEntrarCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/usuarios': {
      id: '/app/admin/usuarios'
      path: '/usuarios'
      fullPath: '/app/admin/usuarios'
      preLoaderRoute: typeof AppAdminUsuariosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/planos': {
      id: '/app/admin/planos'
      path: '/planos'
      fullPath: '/app/admin/planos'
      preLoaderRoute: typeof AppAdminPlanosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/estacoes': {
      id: '/app/admin/estacoes'
      path: '/estacoes'
      fullPath: '/app/admin/estacoes'
      preLoaderRoute: typeof AppAdminEstacoesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/conteudo': {
      id: '/app/admin/conteudo'
      path: '/conteudo'
      fullPath: '/app/admin/conteudo'
      preLoaderRoute: typeof AppAdminConteudoRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/sala/$code/': {
      id: '/app/sala/$code/'
      path: '/sala/$code'
      fullPath: '/app/sala/$code/'
      preLoaderRoute: typeof AppSalaCodeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sala/$code/paciente': {
      id: '/app/sala/$code/paciente'
      path: '/sala/$code/paciente'
      fullPath: '/app/sala/$code/paciente'
      preLoaderRoute: typeof AppSalaCodePacienteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sala/$code/candidato': {
      id: '/app/sala/$code/candidato'
      path: '/sala/$code/candidato'
      fullPath: '/app/sala/$code/candidato'
      preLoaderRoute: typeof AppSalaCodeCandidatoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sala/$code/banca': {
      id: '/app/sala/$code/banca'
      path: '/sala/$code/banca'
      fullPath: '/app/sala/$code/banca'
      preLoaderRoute: typeof AppSalaCodeBancaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/professor/estacoes/$id': {
      id: '/app/professor/estacoes/$id'
      path: '/$id'
      fullPath: '/app/professor/estacoes/$id'
      preLoaderRoute: typeof AppProfessorEstacoesIdRouteImport
      parentRoute: typeof AppProfessorEstacoesRoute
    }
    '/app/professor/correcoes/$id': {
      id: '/app/professor/correcoes/$id'
      path: '/$id'
      fullPath: '/app/professor/correcoes/$id'
      preLoaderRoute: typeof AppProfessorCorrecoesIdRouteImport
      parentRoute: typeof AppProfessorCorrecoesRoute
    }
    '/app/admin/estacoes/$id': {
      id: '/app/admin/estacoes/$id'
      path: '/$id'
      fullPath: '/app/admin/estacoes/$id'
      preLoaderRoute: typeof AppAdminEstacoesIdRouteImport
      parentRoute: typeof AppAdminEstacoesRoute
    }
  }
}

interface AppAdminEstacoesRouteChildren {
  AppAdminEstacoesIdRoute: typeof AppAdminEstacoesIdRoute
}

const AppAdminEstacoesRouteChildren: AppAdminEstacoesRouteChildren = {
  AppAdminEstacoesIdRoute: AppAdminEstacoesIdRoute,
}

const AppAdminEstacoesRouteWithChildren =
  AppAdminEstacoesRoute._addFileChildren(AppAdminEstacoesRouteChildren)

interface AppAdminRouteChildren {
  AppAdminConteudoRoute: typeof AppAdminConteudoRoute
  AppAdminEstacoesRoute: typeof AppAdminEstacoesRouteWithChildren
  AppAdminPlanosRoute: typeof AppAdminPlanosRoute
  AppAdminUsuariosRoute: typeof AppAdminUsuariosRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminConteudoRoute: AppAdminConteudoRoute,
  AppAdminEstacoesRoute: AppAdminEstacoesRouteWithChildren,
  AppAdminPlanosRoute: AppAdminPlanosRoute,
  AppAdminUsuariosRoute: AppAdminUsuariosRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppProfessorCorrecoesRouteChildren {
  AppProfessorCorrecoesIdRoute: typeof AppProfessorCorrecoesIdRoute
}

const AppProfessorCorrecoesRouteChildren: AppProfessorCorrecoesRouteChildren = {
  AppProfessorCorrecoesIdRoute: AppProfessorCorrecoesIdRoute,
}

const AppProfessorCorrecoesRouteWithChildren =
  AppProfessorCorrecoesRoute._addFileChildren(
    AppProfessorCorrecoesRouteChildren,
  )

interface AppProfessorEstacoesRouteChildren {
  AppProfessorEstacoesIdRoute: typeof AppProfessorEstacoesIdRoute
}

const AppProfessorEstacoesRouteChildren: AppProfessorEstacoesRouteChildren = {
  AppProfessorEstacoesIdRoute: AppProfessorEstacoesIdRoute,
}

const AppProfessorEstacoesRouteWithChildren =
  AppProfessorEstacoesRoute._addFileChildren(AppProfessorEstacoesRouteChildren)

interface AppProfessorRouteChildren {
  AppProfessorCorrecoesRoute: typeof AppProfessorCorrecoesRouteWithChildren
  AppProfessorEstacoesRoute: typeof AppProfessorEstacoesRouteWithChildren
  AppProfessorFlashcardsRoute: typeof AppProfessorFlashcardsRoute
  AppProfessorResumosRoute: typeof AppProfessorResumosRoute
  AppProfessorIndexRoute: typeof AppProfessorIndexRoute
}

const AppProfessorRouteChildren: AppProfessorRouteChildren = {
  AppProfessorCorrecoesRoute: AppProfessorCorrecoesRouteWithChildren,
  AppProfessorEstacoesRoute: AppProfessorEstacoesRouteWithChildren,
  AppProfessorFlashcardsRoute: AppProfessorFlashcardsRoute,
  AppProfessorResumosRoute: AppProfessorResumosRoute,
  AppProfessorIndexRoute: AppProfessorIndexRoute,
}

const AppProfessorRouteWithChildren = AppProfessorRoute._addFileChildren(
  AppProfessorRouteChildren,
)

interface AppResumosRouteChildren {
  AppResumosIdRoute: typeof AppResumosIdRoute
}

const AppResumosRouteChildren: AppResumosRouteChildren = {
  AppResumosIdRoute: AppResumosIdRoute,
}

const AppResumosRouteWithChildren = AppResumosRoute._addFileChildren(
  AppResumosRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppEstacoesRoute: typeof AppEstacoesRoute
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppProfessorRoute: typeof AppProfessorRouteWithChildren
  AppProgressoRoute: typeof AppProgressoRoute
  AppResumosRoute: typeof AppResumosRouteWithChildren
  AppTreinarRoute: typeof AppTreinarRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEntrarCodeRoute: typeof AppEntrarCodeRoute
  AppResultadoIdRoute: typeof AppResultadoIdRoute
  AppSimulacaoIdRoute: typeof AppSimulacaoIdRoute
  AppSimuladoIdRoute: typeof AppSimuladoIdRoute
  AppSalaCodeBancaRoute: typeof AppSalaCodeBancaRoute
  AppSalaCodeCandidatoRoute: typeof AppSalaCodeCandidatoRoute
  AppSalaCodePacienteRoute: typeof AppSalaCodePacienteRoute
  AppSalaCodeIndexRoute: typeof AppSalaCodeIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppEstacoesRoute: AppEstacoesRoute,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppProfessorRoute: AppProfessorRouteWithChildren,
  AppProgressoRoute: AppProgressoRoute,
  AppResumosRoute: AppResumosRouteWithChildren,
  AppTreinarRoute: AppTreinarRoute,
  AppIndexRoute: AppIndexRoute,
  AppEntrarCodeRoute: AppEntrarCodeRoute,
  AppResultadoIdRoute: AppResultadoIdRoute,
  AppSimulacaoIdRoute: AppSimulacaoIdRoute,
  AppSimuladoIdRoute: AppSimuladoIdRoute,
  AppSalaCodeBancaRoute: AppSalaCodeBancaRoute,
  AppSalaCodeCandidatoRoute: AppSalaCodeCandidatoRoute,
  AppSalaCodePacienteRoute: AppSalaCodePacienteRoute,
  AppSalaCodeIndexRoute: AppSalaCodeIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  ECodeRoute: ECodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
